package com.antor.f2p.engine.core;

import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.logging.Logger;

/**
 * Thread-safe, TTL-based message deduplication cache.
 * <p>
 * Prevents the same message from being processed more than once when it
 * arrives via multiple paths (e.g., direct broadcast + relay hop).
 * </p>
 *
 * <h3>How it works</h3>
 * Each outbound message should carry a globally unique {@code message_id}
 * (typically a UUID generated by the sender). When a message arrives at
 * any entry point (UDP listener, relay processor, etc.), the receiver
 * calls {@link #trySeen(String)}. If the method returns {@code false},
 * the message was already processed and should be silently dropped.
 *
 * <h3>Eviction</h3>
 * Old entries are evicted based on a configurable TTL (default 60 seconds).
 * A background daemon thread runs every {@code evictionIntervalMs} to
 * purge stale entries, preventing unbounded memory growth.
 */
public class MessageDeduplicator {

    private static final Logger LOG = Logger.getLogger(MessageDeduplicator.class.getName());

    /** Default TTL for seen message IDs (ms). */
    public static final long DEFAULT_TTL_MS = 60_000;

    /** Default interval between eviction sweeps (ms). */
    public static final long DEFAULT_EVICTION_INTERVAL_MS = 30_000;

    /** Upper bound on the number of entries before a forced eviction. */
    private static final int MAX_CAPACITY = 10_000;

    private final ConcurrentHashMap<String, Long> seenMessages;
    private final long ttlMs;
    private final AtomicBoolean running;

    private ScheduledExecutorService evictionScheduler;

    /** Creates a deduplicator with default TTL (60 s) and auto-eviction. */
    public MessageDeduplicator() {
        this(DEFAULT_TTL_MS);
    }

    /**
     * Creates a deduplicator with the specified TTL and auto-eviction.
     *
     * @param ttlMs how long a message ID is remembered (milliseconds)
     */
    public MessageDeduplicator(long ttlMs) {
        this.seenMessages = new ConcurrentHashMap<>();
        this.ttlMs = ttlMs > 0 ? ttlMs : DEFAULT_TTL_MS;
        this.running = new AtomicBoolean(false);
    }

    // ---------------------------------------------------------------
    //  Lifecycle
    // ---------------------------------------------------------------

    /** Starts the background eviction thread. */
    public void start() {
        if (running.getAndSet(true)) return;
        evictionScheduler = Executors.newSingleThreadScheduledExecutor(r -> {
            Thread t = new Thread(r, "msg-dedup-eviction");
            t.setDaemon(true);
            return t;
        });
        evictionScheduler.scheduleAtFixedRate(
                this::evictExpired,
                DEFAULT_EVICTION_INTERVAL_MS,
                DEFAULT_EVICTION_INTERVAL_MS,
                TimeUnit.MILLISECONDS
        );
        LOG.fine("MessageDeduplicator started (ttl=" + ttlMs + "ms)");
    }

    /** Stops the background eviction thread and clears all entries. */
    public void stop() {
        running.set(false);
        if (evictionScheduler != null) {
            evictionScheduler.shutdownNow();
            evictionScheduler = null;
        }
        seenMessages.clear();
        LOG.fine("MessageDeduplicator stopped");
    }

    // ---------------------------------------------------------------
    //  Core API
    // ---------------------------------------------------------------

    /**
     * Attempts to mark a message ID as seen.
     *
     * @param messageId the unique identifier of the incoming message
     * @return {@code true} if this is the <b>first</b> time this ID has
     *         been seen (proceed with processing); {@code false} if it
     *         was already seen (this is a duplicate — drop it)
     */
    public boolean trySeen(String messageId) {
        if (messageId == null || messageId.isEmpty()) {
            return true; // cannot deduplicate without an ID — allow through
        }

        long now = System.currentTimeMillis();
        Long previous = seenMessages.putIfAbsent(messageId, now);

        if (previous != null) {
            // Already seen — this is a duplicate
            LOG.fine("Duplicate message detected: " + messageId);
            return false;
        }

        // Force eviction if we exceed capacity (prevents OOM under attack)
        if (seenMessages.size() > MAX_CAPACITY) {
            evictExpired();
        }

        return true;
    }

    /**
     * Returns {@code true} if the given message ID has already been
     * registered (regardless of TTL).
     */
    public boolean contains(String messageId) {
        return messageId != null && seenMessages.containsKey(messageId);
    }

    /** Returns the number of message IDs currently in the cache. */
    public int size() {
        return seenMessages.size();
    }

    // ---------------------------------------------------------------
    //  Internal
    // ---------------------------------------------------------------

    /** Evicts entries whose TTL has expired. */
    private void evictExpired() {
        long cutoff = System.currentTimeMillis() - ttlMs;
        int before = seenMessages.size();
        seenMessages.values().removeIf(timestamp -> timestamp < cutoff);
        int after = seenMessages.size();
        int removed = before - after;
        if (removed > 0) {
            LOG.fine("Evicted " + removed + " expired message IDs ("
                    + after + " remain)");
        }
    }
}
